### ISSUE TITLE
proftpd 1.3.6 compatibility

### ISSUE THREAD

**Issue by dup2** [Castaglia/proftpd-mod_diskuse#4]
Hi TJ

I'm trying to compile this module for proftpd 1.3.6 and get errors about missing functions like 'pr_user_or_expression' and 'pr_group_and_expression' and similar.

Did the API change and is this module thus not compatible anymore? 

Thanks.

**Comment by Castaglia** [comment]
This should now be fixed in master.  Thanks!

**Comment by dup2** [comment]
Great!
